apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: eleanor-aws-autoscaling

namespace: eleanor

resources:
  - ../  # Include base AWS overlay
  - karpenter/provisioner.yaml
  - karpenter/node-templates.yaml

components:
  - ../../../components/keda
  - ../../../components/vpa
  - ../../../components/prometheus
  - ../../../components/metrics-adapter

commonLabels:
  autoscaling: enabled
  autoscaler: karpenter
