apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: eleanor-gcp-autoscaling

namespace: eleanor

resources:
  - ../  # Include base GCP overlay
  - node-pools.yaml

components:
  - ../../../components/keda
  - ../../../components/vpa
  - ../../../components/prometheus
  - ../../../components/metrics-adapter

commonLabels:
  autoscaling: enabled
  autoscaler: gke-cluster-autoscaler
